[physical-ports]
enable = false
device-rules = [
    {allow = true, id = "1a2c:4c5e", name = "USB Keyboard"}, # allow only at that port
    {allow = true, id = "04f3:0c00", name = "ELAN:ARM-M4"},
    {allow = false, id = "1a3d:5b4e", name = "USB Mouse"}
]
port-rules = [
    {allow = false, id = "1-3", name = "USB Keyboard"}, # block all devices at that port
    {allow = true, id = "1-2", name = "USB Mouse"}
]

[file-systems]
# Basic
block = {udf = false, cramfs = true, squashfs = false}
# Intermediate
configure_fs = {tmp = true, dev_shm = true} # /tmp and /dev/shm
tmp_size = 2 # in GB
disable_automount = false
# Advanced
enable_aide = true # Advanced Intrusion Detection Environment

[processes] # Process Hardening
enable_aslr = true # Address Space Layout Randomization
remove_prelink = true
disable_error_reporting = true
restrict_core_dumps = true

[apparmor] # Mandatory Access Control
enable = true
mode = "complain" # enforce, complain

[gdm] # GNOME Display Manager
remove = false
disable_user_list = true
enable_lock_on_idle = true
lock_on_idle = 100 # in seconds, 0 to disable
no_override_lockscreen = true
disable_automount = false
lock_automount = false
disable_autorun = true
no_override_autorun = true

[time-sync] # Time synchronization
enable_ntp = true
enable_ntp_servers = true
ntp_servers = ["http://time-a-g.nist.gov/", "132.163.97.3", "http://time-d-b.nist.gov/"]
enable_ntp_user = true

[services] # Services
remove_avahi = true
remove_cups = true
remove_dhcp = true
remove_ldap = true
remove_nfs = true
remove_ftp = true
remove_http = true
remove_imap_pop3 = true
remove_samba = true
remove_http_proxy = true
remove_snmp = true
remove_nis = true
remove_rsync = true

[service_clients] # Service Clients
remove_nis = true
remove_rsh = true
remove_talk = true
remove_telnet = true
remove_ldap = true
remove_rpc = true

[network] # Network
disable_wireless = true # WiFi and other wireless interfaces
disable_packet_redirects = true
disable_ip_forwarding = true
reject_source_routed_packets = true
reject_icmp_redirects = true
reject_secure_icmp_redirects = true
log_suspicious_packets = true
ignore_broadcasts = true
ignore_bogus_icmp_errors = true
enable_rp_filter = true # Reverse Path Filtering
enable_syn_cookies = true # TCP SYN Cookie
reject_ipv6_router_adv = true # IPv6 Router Advertisement
disable_protocols = {dccp = false, sctp = false, rds = false, tipc = false}

[firewall] # Firewall
enable = true
configure_loopback_traffic = true # Allow loopback traffic
enable_default_deny = true # Deny all traffic by default

[ssh]
configure_permissions = {sshd_config = true, private_host_key = true, public_host_key = true}
enable_allow_users = true # 
allow_users = ["user1", "user2"]
enable_allow_groups = true #
allow_groups = ["group1", "group2"]
enable_log_level = true #
log_level = "VERBOSE" # INFO, VERBOSE
enable_pam = true 
disable_root_login = true
disable_host_based_auth = true
disable_permit_empty_passwords = true
disable_permit_user_env = true
enable_ignore_rhosts = true 
disable_x11_forwarding = true
enable_strong_ciphers = true
enable_strong_mac_algorithms = true
enable_strong_key_exchange_algorithms = true
disable_tcp_forwarding = false
configure_warning_banner = true
configure_max_startups = true
enable_max_auth_tries = true
max_auth_tries = 4
enable_max_sessions = true
max_sessions = 10
enable_login_grace_time = true #
login_grace_time = 60 # in seconds
enable_client_alive_interval = true #
client_alive_interval = 300 # in seconds
enable_client_alive_count_max = true #
client_alive_count_max = 3

[privilege_escalation] # Privilege Escalation
use_pty = true
enable_logfile = true
disable_nopassword = false
enable_reauthentication = true
enable_authentication_timeout = true
authentication_timeout = 15 # in minutes
restrict_su = true

[pam] # Pluggable Authentication Modules
enable_password_level = true
required_password_level = "strong" # weak, medium, strong, stronger
enable_password_length = true
minimum_password_length = 14
limit_password_reuse = true
password_reuse_limit = 5
configure_hashing_algorithm = true
