[physical-ports]
enable = false
device-rules = [
    {allow = true, id = "1a2c:4c5e", name = "USB Keyboard"}, # allow only at that port
    {allow = true, id = "04f3:0c00", name = "ELAN:ARM-M4"},
    {allow = false, id = "1a3d:5b4e", name = "USB Mouse"}
]
port-rules = [
    {allow = false, id = "1-3", name = "USB Keyboard"}, # block all devices at that port
    {allow = true, id = "1-2", name = "USB Mouse"}
]

[file-systems]
# Basic
block = {udf = true, cramfs = true, squashfs = true}
# Intermediate
configure_fs = {tmp = true, dev_shm = true} # /tmp and /dev/shm
tmp_size = 2 # in GB
disable_automount = false
# Advanced
enable_aide = true # Advanced Intrusion Detection Environment

[processes] # Process Hardening
enable_aslr = true # Address Space Layout Randomization
remove_prelink = true
disable_error_reporting = true
restrict_core_dumps = true

[apparmor] # Mandatory Access Control
enable = true
mode = "complain" # enforce, complain

[gdm] # GNOME Display Manager
remove = false
disable_user_list = false
enable_lock_on_idle = false
lock_on_idle = 100 # in seconds, 0 to disable
no_override_lockscreen = false
disable_automount = false
lock_automount = false
disable_autorun = false
no_override_autorun = false

[time-sync] # Time synchronization
enable_ntp = true
enable_ntp_servers = true
ntp_servers = ["http://time-a-g.nist.gov/", "132.163.97.3", "http://time-d-b.nist.gov/"]
enable_ntp_user = true

[services] # Services
remove_avahi = true
remove_cups = true
remove_dhcp = true
remove_ldap = true
remove_nfs = true
remove_ftp = true
remove_http = true
remove_imap_pop3 = true
remove_samba = true
remove_http_proxy = true
remove_snmp = true
remove_nis = true
remove_rsync = true

[service_clients] # Service Clients
remove_nis = true
remove_rsh = true
remove_talk = true
remove_telnet = true
remove_ldap = true
remove_rpc = true

[network] # Network
disable_wireless = false # WiFi and other wireless interfaces
disable_packet_redirects = false
disable_ip_forwarding = false
reject_source_routed_packets = false
reject_icmp_redirects = false
reject_secure_icmp_redirects = false
log_suspicious_packets = false
ignore_broadcasts = false
ignore_bogus_icmp_errors = false
enable_rp_filter = false # Reverse Path Filtering
enable_syn_cookies = false # TCP SYN Cookie
reject_ipv6_router_adv = false # IPv6 Router Advertisement
disable_protocols = {dccp = false, sctp = false, rds = false, tipc = false}

[firewall] # Firewall
enable = true
configure_loopback_traffic = true # Allow loopback traffic
enable_default_deny = false # Deny all traffic by default

[ssh]
configure_permissions = {sshd_config = false, private_host_key = false, public_host_key = false}
enable_allow_users = false # 
allow_users = ["user1", "user2"]
enable_allow_groups = false #
allow_groups = ["group1", "group2"]
enable_log_level = false #
log_level = "VERBOSE" # INFO, VERBOSE
enable_pam = false 
disable_root_login = false
disable_host_based_auth = false
disable_permit_empty_passwords = false
disable_permit_user_env = false
enable_ignore_rhosts = false 
disable_x11_forwarding = false
enable_strong_ciphers = false
enable_strong_mac_algorithms = false
enable_strong_key_exchange_algorithms = false
disable_tcp_forwarding = false
configure_warning_banner = false
configure_max_startups = false
enable_max_auth_tries = false
max_auth_tries = 4
enable_max_sessions = false
max_sessions = 10
enable_login_grace_time = false #
login_grace_time = 60 # in seconds
enable_client_alive_interval = false #
client_alive_interval = 300 # in seconds
enable_client_alive_count_max = false #
client_alive_count_max = 3

[privilege_escalation] # Privilege Escalation
use_pty = false
enable_logfile = false
disable_nopassword = false
enable_reauthentication = false
enable_authentication_timeout = false
authentication_timeout = 15 # in minutes
restrict_su = false

[pam] # Pluggable Authentication Modules
enable_password_level = false
required_password_level = "strong" # weak, medium, strong, stronger
enable_password_length = false
minimum_password_length = 14
limit_password_reuse = false
password_reuse_limit = 5
configure_hashing_algorithm = false