[physical-ports]
enable = "Defines a point of entry for communication "
device-rules = "Dynamically creates and removes nodes for hardware devices."
    
port-rules ="Lets administrators manage network services on Ubuntu systems by opening and closing ports."

[file-systems]
# Basic
block = {udf = "Storing information on the DVD (Digital Versatile Disc or Digital Video Disc) optical media", cramfs = "Designed to be simple and small, and to compress things well", squashfs = "Squashfs is a compressed read-only filesystem for Linux"}
# Intermediate
configure_fs = {tmp = "Used for programs that require temporary files ", dev_shm = "Allows Linux programs to efficiently pass data between each other"} # /tmp and /dev/shm
tmp_size = "How much space is available in tmp in your system  "
disable_automount = "Prevents Windows from automatically mounting or assigning drive letters to any new basic volumes that are visible to the system"
# Advanced
enable_aide = "To verify the integrity of the files"

[processes] # Process Hardening
enable_aslr = "Technique that is used to increase the difficulty of performing a buffer overflow attack that requires the attacker to know the location of an executable in memory."
remove_prelink = "Time needed for the dynamic linker to perform relocations at startup significantly decreases."
disable_error_reporting = "Counts, analyzes, and aggregates the crashes in your running cloud services."
restrict_core_dumps = "The system provides the ability to set a soft limit for core dumps, but this can be overridden by the user."

[apparmor] # Mandatory Access Control
enable = "A Linux Security Module implementation of name-based mandatory access controls"   
mode = "Enforces the SELinux policy and denies access based on SELinux policy rules" 

[gdm] # GNOME Display Manager
remove = "Uninstalls the desktop environment "
disable_user_list = "Controls if a list of users is displayed on the login screen."
lock_on_idle = "Screen inactivity idle time interval"
no_override_lockscreen = "Override the static lock screen image with a snapshot of your current live wallpaper."
disable_automount = "Prevents Windows from automatically mounting or assigning drive letters to any new basic volumes that are visible to the system"
lock_automount = "Installs autofs mount points and associates the information in the automaster"
disable_autorun = "Windows will no longer open these devices automatically."
no_override_autorun = "The NoDriveAutoRun value disables AutoRun for specified drive letters"

[time-sync] # Time synchronization
enable_ntp = "Your device contacts an NTP server to synchronize the time."
ntp_servers = "Allows the synchronization of system clocks (from desktops to servers)."
enable_ntp_user = "To automatically get the correct time from NTP servers on the Internet to set the system clock."

[services] # Services
remove_avahi = "Used for name resolution and service discovery within the local network."
remove_cups = "Allows a computer to act as a print server."
remove_dhcp = "Deletes the specified Dynamic Host Configuration Protocol (DHCP) server service from the list of authorized DHCP server services"
remove_ldap = "Helps users find data about organizations, persons, and more."
remove_nfs = "A mechanism for storing files on a network."
remove_ftp = "Transfer of files from one host to another over a TCP-based network, such as the Internet"
remove_http = "Used to load webpages using hypertext links"
remove_imap_pop3 = "Email protocols used to access and manage emails on remote servers"
remove_samba = "Enables Linux / Unix machines to communicate with Windows machines in a network."
remove_http_proxy = "Help businesses detect and block suspicious traffic, protecting web servers from external cyberattacks."
remove_snmp = "Monitor and manage network devices connected over an IP."
remove_nis = "Allows you to maintain consistent configuration files throughout your network."
remove_rsync = "Transferring and synchronizing files between local and remote devices."

[service_clients] # Service Clients
remove_nis = "Allows you to maintain consistent configuration files throughout your network."
remove_rsh = "Enables you to execute a command on a remote host and receive the results on your local host."
remove_talk = "Allows two users on the same host or on different hosts to have an interactive conversation."
remove_telnet = "Create a remote connection with a system over a TCP/IP network."
remove_ldap = "Helps users find data about organizations, persons, and more"
remove_rpc = "To call other processes on the remote systems like a local system."


[network] # Network
disable_wireless = "Support and facilitate the configuration of device drivers of wireless network interface controllers and some related aspects of networking"
disable_packet_redirects = "To send routing information to other hosts"
disable_ip_forwarding = "Having more efficient routing of network packets."
reject_source_routed_packets = "Allows an IP packet to carry information, a list of addresses, that tells a router the path the packet must take"
reject_icmp_redirects = "For having more efficient routing of network packets."
reject_secure_icmp_redirects = "The same as ICMP redirects, except they come from gateways listed on the default gateway list."
log_suspicious_packets = "Monitoring and detecting security issues."
ignore_broadcasts = "A network address used to transmit to all devices connected to a multiple-access communications network"
ignore_bogus_icmp_errors = "Prevents the kernel from logging bogus responses (RFC-1122 non-compliant) from broadcast reframes"
enable_rp_filter = "Protects against spoofed source addresses by causing the system to discard packets"
enable_syn_cookies = " A technique used to resist SYN flood attacks"
reject_ipv6_router_adv =  "Allows devices to use a much larger number of unique IP addresses"
disable_protocols = {dccp = "To solve issues present in UDP and TCP, particularly for real-time and multimedia (streaming) traffic.", sctp = "Ensures reliable, in-sequence transport of data", rds = "A connectionless and record-oriented protocol that provides an in-order and no-duplicate service over InfiniBand", tipc = "If the protocol is not being used, it is recommended that kernel module not be loaded, "}


[firewall] # Firewall
enable = "A way to protect machines from any unwanted traffic from outside."
configure_loopback_traffic = "A virtual network interface that doesn't represent any physical or hardware device."
enable_default_deny = " Deny all traffic by default "

[ssh]
enable = "A network protocol that gives users, particularly system administrators, a secure way to access a computer over an unsecured network."
port = "Port number 22"
permit-empty-passwords = "Anybody may log in as that user without providing a password."
password-authentication = "User to enter their credentials — username and password — in order to confirm their identity."
permit-root-login = "User account for administrative purposes, and typically has the highest access rights on the system."
client-alive-interval = "A time out interval specified in seconds "
client-alive-count-max = "Sets the number of client alive messages which may be sent without sshd receiving any messages back from the client."
allow-users = "Allow SSH access for a user "
allow-groups = "Allow SSH access for an entire group,"
x11-forwarding = " Amechanism that allows a user to start up remote applications, and then forward the application display to their local Windows machine"

[privilege_escalation] # Privilege Escalation
use_pty = "A process finds an unused pseudoterminal pair by trying to open(2) each pseudoterminal master until an open succeeds"
enable_logfile = "Monitoring and detecting security issues"
disable_nopassword = "Changes the login password or password phrase for the user ID specified. "
enable_reauthentication = "Authentication is the formal sysadmin term for logging into the system"
authentication_timeout = "Allows you to run a command with a time limit" # in minutes
restrict_su = "Su is to get superuser privileges. "
