[physical-ports]

enable = "Defines a point of entry for communication"

device-rules = "Dynamically creates and removes nodes for hardware devices."

port-rules ="Lets administrators manage network services on Ubuntu systems by opening and closing ports."

[file-systems]

Basic
block = {udf = "Storing information on the CD/DVD (Compact Disc/Digital Versatile Disc or Digital Video Disc) optical media", cramfs = "Designed to be simple and small, and to compress things well", squashfs = "Squashfs is a compressed read-only filesystem for Ubuntu used in snaps "}

Intermediate
configure_fs = {tmp = "Used for programs that require temporary files ", dev_shm = "Allows Ubuntu programs to efficiently pass data between each other"} # /tmp and /dev/shm

tmp_size = "How much space is available in /tmp in your system "

disable_automount = "Prevents Ubuntu from automatically mounting or assigning mount points to any new basic volumes that are visible to the system"

Advanced
enable_aide = " Ace Integrated Development Environment."

[processes] # Process Hardening

enable_aslr = "Technique that is used to increase the difficulty of performing a buffer overflow attack that requires the attacker to know the location of an executable in memory."

remove_prelink = "Time needed for the dynamic linker to perform relocations at startup significantly decreases."

disable_error_reporting = "Counts, analyzes, and aggregates the crashes in your running cloud services."

restrict_core_dumps = "The system provides the ability to set a soft limit for core dumps, but this can be overridden by the user."

[apparmor] # Mandatory Access Control

enable = "An Ubuntu Security Module implementation of name-based mandatory access controls"

mode = "Enforces the SELinux policy and denies access based on SELinux policy rules"

[gdm] # GNOME Display Manager

remove = "Uninstalls the desktop environment "

disable_user_list = "Controls if a list of users is displayed on the login screen."

lock_on_idle = "Screen inactivity idle time interval"

no_override_lockscreen = "Override the static lock screen image with a snapshot of your current live wallpaper."

disable_automount = "Prevents Ubuntu from automatically mounting or assigning mount points to any new basic volumes that are visible to the system"

lock_automonut = "Installs autofs mount points and associates the information in the automaster"

disable_autorun = "Ubuntu will no longer open these devices automatically."

no_override_autorun = "The NoDriveAutoRun value disables AutoRun for specified drive letters"

[time-sync] # Time synchronization

enable_ntp = "Your device contacts an NTP server to synchronize the time."

ntp_servers = "Allows the synchronization of system clocks (from desktops to servers)."

enable_ntp_user = "To automatically get the correct time from NTP servers on the Internet to set the system clock."

[services] # Services

remove_avahi = "Used for name resolution and service discovery within the local network."

remove_cups = "Allows a computer to act as a print server."

remove_dhcp = "Deletes the specified Dynamic Host Configuration Protocol (DHCP) server service from the list of authorized DHCP server services"

remove_ldap = "Helps users find data about organizations, persons, and more."

remove_nfs = "A mechanism for storing files on a network."

remove_ftp = "Transfer of files from one host to another over a TCP-based network, such as the Internet"

remove_http = "Used to load webpages using hypertext links"

remove_imap_pop3 = "Email protocols used to access and manage emails on remote servers"

remove_samba = "Enables Ubuntu / Unix machines to communicate with Windows machines in a network."

remove_http_proxy = "Help businesses detect and block suspicious traffic, protecting web servers from external cyberattacks."

remove_snmp = "Monitor and manage network devices connected over an IP."

remove_nis = "Allows you to maintain consistent configuration files throughout your network."

remove_rsync = "Transferring and synchronizing files between local and remote devices."

[service_clients] # Service Clients

remove_nis = "Allows you to maintain consistent configuration files throughout your network."

remove_rsh = "Enables you to execute a command on a remote host and receive the results on your local host."

remove_talk = "Allows two users on the same host or on different hosts to have an interactive conversation."

remove_telnet = "Create a remote connection with a system over